force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>inwise Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inwise Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inwise Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account__c.Owner:User.Id</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <label>Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Picklist_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Sendid__c.field-meta.xml
<CustomField>
    <fullName>Sendid__c</fullName>
    <label>Sendid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Logs__c/Error_Logs__c.object-meta.xml
<CustomObject>
    <label>inwise Error Logs</label>
    <nameField>
        <displayFormat>ILN-{0000}</displayFormat>
        <label>Logs No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>inwise Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Logs__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logs__c/fields/Run_By__c.field-meta.xml
<CustomField>
    <fullName>Run_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Run By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Logs__c/fields/Run_On__c.field-meta.xml
<CustomField>
    <fullName>Run_On__c</fullName>
    <label>Run On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incoming_Webhooks__c/Incoming_Webhooks__c.object-meta.xml
<CustomObject>
    <label>inwise Incoming Webhooks</label>
    <nameField>
        <displayFormat>IW-{0000}</displayFormat>
        <label>Incoming Webhooks Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>inwise Incoming Webhooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Landing_Sync__c/Landing_Sync__c.object-meta.xml
<CustomObject>
    <label>inwise Landing Sync</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inwise Landing Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Landing_Sync__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inwise Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>inwise Landing Sync</relationshipLabel>
    <relationshipName>inwise_Landing_Sync</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Landing_Sync__c/fields/Landing_Page_Id__c.field-meta.xml
<CustomField>
    <fullName>Landing_Page_Id__c</fullName>
    <label>Landing Page/Popup Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Landing_Sync__c/fields/Landing_Page_Name__c.field-meta.xml
<CustomField>
    <fullName>Landing_Page_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Landing Page/Popup Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Landing_Sync__c/fields/Last_JobId__c.field-meta.xml
<CustomField>
    <fullName>Last_JobId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last JobId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Landing_Sync__c/fields/Last_JobName__c.field-meta.xml
<CustomField>
    <fullName>Last_JobName__c</fullName>
    <label>Last JobName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Landing_Sync__c/fields/Record_Index__c.field-meta.xml
<CustomField>
    <fullName>Record_Index__c</fullName>
    <label>Record Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Landing_Sync_History__c/Landing_Sync_History__c.object-meta.xml
<CustomObject>
    <label>inwise Landing Sync History</label>
    <nameField>
        <displayFormat>LSHN-{0000}</displayFormat>
        <label>Landing Sync History No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>inwise Landing Sync History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Landing_Sync_History__c/fields/Landing_Sync__c.field-meta.xml
<CustomField>
    <fullName>Landing_Sync__c</fullName>
    <label>inwise Landing Sync</label>
    <referenceTo>Landing_Sync__c</referenceTo>
    <relationshipLabel>inwise Landing Sync History</relationshipLabel>
    <relationshipName>inwise_Landing_Sync_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Landing_Sync_History__c/fields/Run_By__c.field-meta.xml
<CustomField>
    <fullName>Run_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Run By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inwise_Landing_Sync_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Logs__c/Logs__c.object-meta.xml
<CustomObject>
    <label>inwise Logs</label>
    <nameField>
        <displayFormat>ILN-{0000}</displayFormat>
        <label>Logs No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>inwise Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logs__c/fields/Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Api_Name__c</fullName>
    <label>Api Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Method Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Run_By__c.field-meta.xml
<CustomField>
    <fullName>Run_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Run By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inwise_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settings__c/Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>inwise Setting</label>
</CustomObject>

force-app/main/default/objects/Settings__c/fields/Activate_Advanced_Features__c.field-meta.xml
<CustomField>
    <fullName>Activate_Advanced_Features__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activate Advanced Features</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/Landing_Sync_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Landing_Sync_Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Landing Sync Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/Track_Logs__c.field-meta.xml
<CustomField>
    <fullName>Track_Logs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable or disable to track http logs</description>
    <label>Track Logs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sync_Master__c/Sync_Master__c.object-meta.xml
<CustomObject>
    <label>inwise Sync Process</label>
    <nameField>
        <displayFormat>ISM-{0000}</displayFormat>
        <label>inwise Sync Master No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>inwise Sync Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Master__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>inwise_Sync_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sync_Master__c/fields/Total_Memerbs_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Memerbs_Count__c</fullName>
    <label>Total Memerbs Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Token_Setting__c/Token_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inwise Token Setting</label>
</CustomObject>

force-app/main/default/objects/Token_Setting__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Inwise Account Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InwiseSettingsControllerTest.cls
/******************************************************************************************
*Created By:  Kapil Goutam
*Created On: 
*Purpose :  Test class for inwiseSettingController
* * -----------------------------------------------------
* Modified On       Modified By     Purpose
* 05/29/2019        Kapil Goutam    code coverage
/******************************************************************************************/

@isTest
public class InwiseSettingsControllerTest {
    
    @isTest 
    static void settingsTest() {

        Token_Setting__c tokenSetting = inwiseTestDataFactory.GetInwiseTokenSetting();
        insert tokenSetting;  
        
        Account__c act1 = inwiseTestDataFactory.GetInwiseAccount();
        act1.Default__c = true;
        insert act1;

        tokenSetting.Account_Id__c = act1.Id;
        update tokenSetting;  
        
        Settings__c s = new Settings__c();
        s.name = 'default';
        s.Landing_Sync_Scheduled__c = true;
        insert s;
        
        Error_Logs__c objErrorLog = new Error_Logs__c();
        objErrorLog.Message__c = 'POST_Test';
        objErrorLog.Run_On__c = datetime.now();
        objErrorLog.Class_Name__c = 'TestClass';
        objErrorLog.Method_Name__c = 'TestMethod';
        objErrorLog.Run_By__c = UserInfo.getUserId();
        insert objErrorLog; 
        
        Landing_Sync__c landingSync = new Landing_Sync__c();
        landingSync.Name = 'hello test';
        landingSync.Record_Index__c = 23;
        landingSync.Last_JobId__c = 'hhw';
        landingSync.Landing_Page_Id__c = 22;
        landingSync.Last_JobName__c = 'test 2';
        landingSync.Landing_Page_Name__c = 'test landing';
        insert landingSync;
        
        Test.startTest();
        
        Test.setCurrentPage(Page.inwiseSettings);
        inwiseSettingsController controller = new inwiseSettingsController(new ApexPages.StandardController(act1));
        controller.doReturnCustomSettingUrl();
        Pagereference pagref1 = controller.redirectToListView('Logs__c');
        Pagereference pageref2 = controller.doReturnLogsUrl();
        System.assertEquals(pagref1.geturl(), pageref2.geturl());
        
        Pagereference pagref11 = controller.redirectToListView('Sync_Master__c');
        Pagereference pageref3 = controller.doReturnSyncMasterUrl();
        System.assertEquals(pagref11.geturl(), pageref3.geturl());
        
        System.debug(controller.currentPackageVersion);
        System.debug(controller.turnOnOffTrackLogBtnLabel);
        System.debug(controller.turnOnOffErrorLogBtnLabel);
        System.debug(controller.turnOnOffLandingSyncBtnLabel);
        System.debug(controller.turnOnOffCampaignSyncBtnLabel);
        System.debug(controller.turnOnOffTrackActivityBtnLabel);
        
        Pagereference pagref4 = controller.redirectToListView('Landing_Sync_History__c');
        Pagereference pageref5 = controller.doReturnLandingSyncHistoryUrl();
        System.assertEquals(pagref4.geturl(), pageref5.geturl());
        
        Pagereference pagref6 = controller.redirectToListView('Incoming_Webhooks__c');
        Pagereference pageref7 = controller.doReturnIncomingWebhooksUrl();
        System.assertEquals(pagref6.geturl(), pageref7.geturl());
        
        controller.doClearLogs();
        controller.doClearIncomingWebhooks();
        controller.doSendLogtoinwiseSupport(); 
        controller.doSendErrorLogtoinwiseSupport();
        controller.turnOnOffCampaignSync();
        controller.objInwiseUtil = new InwiseUtil(null);
        controller.turnOnOffCampaignSync();
        controller.doInboundSMSConfiguration();
        controller.toggleSettingLandingSync();
        controller.turnOnOffLandingSync();
        controller.turnOnOffLandingSync();
        controller.objinwiseLtngConstants.isLightning = true;
        controller.doReturnLogsUrl();
        controller.doCheckAndCreateRemoteSite();
        controller.doClearErrorLogs();
        controller.doReturnErrorLogsUrl();
        controller.doClearLandingSync();
        controller.turnOnOffTrackLog(); 
        controller.turnOnOffTrackError();
        controller.turnOnOffTrackActivities();

       
        Test.stopTest();
    }

    @isTest 
    static void settingsTestForGlobalAction() {

        Settings__c s = new Settings__c();
        s.name = 'default';
        s.Landing_Sync_Scheduled__c = true;
        s.Track_Logs__c = true;
        s.Activate_Advanced_Features__c = false;
        insert s;

        Logs__c logs = new Logs__c();
        logs.Api_Name__c = 'POST';
        logs.Class_Name__c = 'inwiseUtiltest';
        logs.Method_Name__c = 'inwiseUtilTest10';
        insert logs;   


        Account__c act1 = inwiseTestDataFactory.GetInwiseAccount();
        act1.Default__c = true;
        insert act1;

        
        Campaign c = new Campaign();
        c.Name = 'test campaign';
        c.Account__c = act1.Id;
        c.Sendid__c = 1237855;
        c.isActive = true;
        c.Campaign_Type__c = 'email';
        insert c;
        
        Sync_Master__c sm = new Sync_Master__c();
        sm.Total_Memerbs_Count__c =3;
        sm.Campaign__c = c.id;
        insert sm;

        // Validate sCONSTContact
        String expectedContactValue = inwiseConstants.SOBJECT_CONTACT;

        // Validate sCONSTLead
        String expectedLeadValue = inwiseConstants.SOBJECT_LEAD;

         // Create an instance of the class
         inwiseGlobalAction actionInstance = new inwiseGlobalAction();
        
         // Set and retrieve the resultMessage property
         actionInstance.resultMessage = 'Test message';


             
        // Test the default constructor
        inwiseGlobalAction actionWithDefaultConstructor = new inwiseGlobalAction();

        Test.startTest();

        inwiseGlobalAction.remoteClearLogs(); 
        inwiseGlobalAction.doClearAll(true);
        inwiseGlobalAction.remoteClearSyncMaster(); 

        inwiseGlobalAction.doClearSyncMaster();
        inwiseGlobalAction.doClearLandingSyncHistory();
        inwiseGlobalAction.doClearPreviousLogs();
        inwiseGlobalAction.remoteTurnOnOffTrackLog(); 
        inwiseGlobalAction.checkAndCreateRemoteSite();
        inwiseGlobalAction.remoteSendLogsToSupport();
        inwiseGlobalAction.initFailedSyncMaster(sm.Id);
        inwiseGlobalAction.remoteinitFailedSyncMaster(sm.Id); 

        inwiseGlobalAction.doSendLogsToSupport();  
        inwiseGlobalAction.getSelectedPicklistOptions('Name', 'Contact');

        Test.stopTest();
    }
}